/** Template contracts for the existing executor. These describe configuration, not permission grants. */
const s = { type: "string" },
  list = { type: "array", items: s },
  values = { type: "array", items: {} },
  o = { type: "object", additionalProperties: true };
const contract = (
  properties: Record<string, any>,
  required: string[],
  outputs: string[],
  effect: string,
) => ({
  inputSchema: {
    type: "object",
    properties,
    required,
    additionalProperties: true,
  },
  outputFields: outputs,
  effect,
});
const recipient = { anyOf: [s, list] };
const draft = {
  to: recipient,
  subject: s,
  text: s,
  connection_id: s,
  communication_id: s,
  provider_thread_id: s,
  in_reply_to: s,
  references: s,
};
export const taskContracts = {
  send_email: contract(
    {
      to: recipient,
      subject: s,
      body: s,
      cc: list,
      bcc: list,
      from: s,
      service_identity_id: s,
      provider_connection_id: s,
      reply_to: recipient,
    },
    ["to", "body"],
    ["communication_id"],
    "Real email only when tenant policy and project email switch allow it",
  ),
  send_sms: contract(
    { to: s, body: s, from: s },
    ["body"],
    ["communication_id"],
    "Real SMS; destination/sender can fall back to configured project/tenant values",
  ),
  outgoing_call: contract(
    {
      to: s,
      from: s,
      instruction: s,
      prompt: s,
      body: s,
      greeting: s,
      purpose_type: s,
    },
    [],
    ["communication_id"],
    "Real phone call; requires resolved destination, sender and instructions",
  ),
  webhook: contract(
    {
      url: s,
      method: { enum: ["GET", "POST", "PUT", "PATCH", "DELETE"] },
      headers: o,
      payload: {},
    },
    ["url"],
    ["webhook_called", "webhook_status", "webhook_response"],
    "Real HTTP call subject to outbound URL controls",
  ),
  write_report: contract(
    {
      prompt: s,
      body: s,
      sop: s,
      template: s,
      eval_criteria: s,
      source_data: {},
      output_schema: o,
    },
    [],
    ["report_content", "structured_output"],
    "AI generation; output_schema selects validated structured output",
  ),
  read_google_doc: contract(
    { resource_name: s },
    [],
    [
      "google_doc_id",
      "google_doc_title",
      "google_doc_revision",
      "google_doc_text",
      "google_doc_read_at",
    ],
    "Read the named or project-allowlisted Google Doc",
  ),
  read_google_sheet: contract(
    { resource_name: s },
    [],
    [
      "google_sheet_id",
      "google_sheet_range",
      "google_sheet_values",
      "google_sheet_read_at",
    ],
    "Read the named or project-allowlisted Sheet",
  ),
  append_google_sheet: contract(
    { resource_name: s, idempotency_key: s, values },
    ["values"],
    ["google_sheet_updated", "google_sheet_write"],
    "Real append; stable idempotency key required (or scheduled occurrence fallback)",
  ),
  upsert_google_sheet: contract(
    {
      resource_name: s,
      idempotency_key: s,
      key_column: { type: "number" },
      key_value: {},
      values,
    },
    ["idempotency_key", "key_column", "key_value", "values"],
    ["google_sheet_updated", "google_sheet_write"],
    "Real allowlisted row upsert",
  ),
  extract_coaching_result: contract(
    {
      instruction: s,
      minimum_confidence: { type: "number", minimum: 0, maximum: 1 },
    },
    [],
    [
      "coaching_summary",
      "coaching_progress",
      "coaching_blockers",
      "coaching_commitments",
      "coaching_next_actions",
      "coaching_evidence_excerpt",
      "coaching_confidence",
      "coaching_requires_review",
      "coaching_extracted_at",
    ],
    "AI extraction from verified transcript in project data or canonical communication",
  ),
  run_email_triage: contract(
    {
      connection_id: s,
      triage_policy: { enum: ["all_inbound", "human_only", "correlated_only"] },
      create_drafts: { type: "boolean" },
      reference_context: {},
      digest_channel: { enum: ["web", "email", "sms"] },
      digest_recipient: s,
    },
    [],
    [
      "triage_items",
      "triage_processed_count",
      "triage_skipped_count",
      "triage_cursor_before",
      "triage_cursor_after",
      "triage_digest_id",
      "triage_digest_summary",
      "triage_last_run_at",
    ],
    "Real mailbox reconciliation/classification and optional draft creation; current project binding required",
  ),
  create_mailbox_draft: contract(
    draft,
    ["to", "subject", "text"],
    ["provider_draft_id", "connection_id", "draft_only"],
    "Create a native draft in the project-selected mailbox; never send",
  ),
  update_mailbox_draft: contract(
    { ...draft, provider_draft_id: s },
    ["provider_draft_id", "to", "subject", "text"],
    ["provider_draft_id", "connection_id", "draft_only"],
    "Update the original native draft in the project-selected mailbox; never send",
  ),
};
