import type { ProjectData } from '../types.js';

/**
 * Compatibility/configuration only.
 *
 * Retry execution is NOT implemented here. Daily coaching retries are ordinary
 * flow primitives (Decision -> Wait -> Loop) generated by projectTemplates.ts.
 * This module exists only so the existing setup UI can read/write the generated
 * template defaults while service projects migrate to direct primitive editing.
 */
export const COACHING_MAX_ATTEMPTS = 2;
export const COACHING_RETRY_DELAY_MINUTES = 10;
export const COACHING_RETRY_WINDOW_MINUTES = 180;

const boundedInteger = (value: unknown, fallback: number, min: number, max: number): number => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(Math.max(Math.floor(parsed), min), max);
};

export const coachingRetryPolicy = (data: ProjectData = {}): {
  maxAttempts: number;
  delayMinutes: number;
  windowMinutes: number;
} => {
  const maxAttempts = boundedInteger(
    data.coaching_retry_attempts ?? data.coaching_max_attempts,
    COACHING_MAX_ATTEMPTS,
    1,
    5
  );
  const delayMinutes = boundedInteger(
    data.coaching_retry_delay_minutes,
    COACHING_RETRY_DELAY_MINUTES,
    5,
    1440
  );
  const windowMinutes = Math.max(
    delayMinutes,
    boundedInteger(data.coaching_retry_window_minutes, COACHING_RETRY_WINDOW_MINUTES, 5, 1440)
  );
  return { maxAttempts, delayMinutes, windowMinutes };
};
