import { Project, Subtask, SubtaskStatus, ReadyCondition } from '../types.js';

/**
 * Extracts variables from a template string (e.g. {{project_name}})
 */
export const extractTemplateVariables = (template: string): string[] => {
  const matches = template.match(/\{\{([^}]+)\}\}/g);
  if (!matches) return [];
  return Array.from(new Set(matches.map(m => m.replace(/[{}]/g, '').trim())));
};

/**
 * Validates a task's ready condition against project data
 */
export const checkReadyCondition = (condition: ReadyCondition, projectData: Record<string, any>): boolean => {
  const value = projectData[condition.variable];
  
  if (condition.exists) {
    return value !== undefined && value !== null;
  }
  
  if (condition.equals !== undefined) {
    return value === condition.equals;
  }
  
  return false;
};

/**
 * Checks all readiness conditions for a single task and returns updated task state
 */
export const evaluateTaskReadiness = (task: Subtask, project: Project): Subtask => {
  if (task.status === SubtaskStatus.STARTED || 
      task.status === 'In Progress' ||
      task.status === SubtaskStatus.SUBMITTED || 
      task.status === SubtaskStatus.COMPLETE || 
      task.status === 'Completed' ||
      task.status === SubtaskStatus.ABANDONED) {
    return task;
  }

  const projectData = project.projectData || {};
  const missingVariables: string[] = [];
  const failedConditions: ReadyCondition[] = [];
  
  // 1. Check template variables
  if (task.templateFile) {
    const requiredVars = extractTemplateVariables(task.templateFile);
    for (const v of requiredVars) {
      if (projectData[v] === undefined || projectData[v] === null) {
        missingVariables.push(v);
      }
    }
  }

  // 2. Check dependencies
  let allDependenciesMet = true;
  if (task.dependsOn && task.dependsOn.length > 0) {
    // Find dependencies within the same project (across all milestones)
    for (const depId of task.dependsOn) {
      let isDepComplete = false;
      for (const m of project.milestones) {
        const depTask = m.subtasks.find(t => t.id === depId);
        if (depTask && depTask.status === SubtaskStatus.COMPLETE) {
          isDepComplete = true;
          break;
        }
      }
      if (!isDepComplete) {
        allDependenciesMet = false;
        break; // Stop checking if one dependency is missed
      }
    }
  }

  // 3. Check optional Boolean ready conditions
  if (task.readyConditions && task.readyConditions.length > 0) {
    for (const condition of task.readyConditions) {
      if (!checkReadyCondition(condition, projectData)) {
        failedConditions.push(condition);
      }
    }
  }

  // 4. Update task status based on checks
  const isReady = missingVariables.length === 0 && failedConditions.length === 0 && allDependenciesMet;
  
  return {
    ...task,
    status: isReady ? SubtaskStatus.READY : SubtaskStatus.NEEDS_PREPARATION,
    missingVariables,
    failedConditions
  };
};

/**
 * Runs readiness checks on all tasks in a project
 */
export const runProjectReadinessCheck = (project: Project): Project => {
  const updatedMilestones = project.milestones.map(milestone => ({
    ...milestone,
    subtasks: milestone.subtasks.map(task => evaluateTaskReadiness(task, project))
  }));

  return {
    ...project,
    milestones: updatedMilestones
  };
};

export const applyTaskApprovalWriteBack = (task: Subtask, project: Project): Project => {
  if (!task.outputVariables || task.outputVariables.length === 0) {
    return project;
  }
  
  const updatedData = { ...project.projectData };
  
  task.outputVariables.forEach(v => {
    if (v.write_on === 'approval' || v.write_on === 'completion') {
      if (v.value_source === 'static') {
        updatedData[v.name] = v.value;
      } else if (v.value_source === 'system_date') {
        updatedData[v.name] = new Date().toISOString().split('T')[0];
      } else if (v.value_source === 'task_output') {
        // e.g., output generated by a person/agent in taskOutput field
        if (task.taskOutput && task.taskOutput[v.name] !== undefined) {
           updatedData[v.name] = task.taskOutput[v.name];
        }
      }
    }
  });

  return {
    ...project,
    projectData: updatedData
  };
};
