import { writeFileSync, readFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";
import { buildOpenApi } from "../lib/http/openapi.js";
import manifest from "../contracts/route-manifest.json";

const spec = buildOpenApi();
const types = astToString(await openapiTS(spec as any));
const index =
  `# Public REST endpoint index\n\nGenerated by \`npm run api:generate\`. ${Object.keys(spec.paths).length} logical paths; ${manifest.length} method/path pairs. Internal dispatcher URLs and automatic HEAD/OPTIONS are excluded. Read [the agent guide](AGENT_API.md) for configuration, authority and testing. See [OpenAPI](../contracts/openapi.json) for schemas and operation discriminators.\n\n| Method | Path | Authority | Capability |\n|---|---|---|---|\n` +
  manifest
    .map(
      (row) =>
        `| ${row.method} | \`${row.path}\` | ${row.authorization.replaceAll("|", "\\|")} | ${row.description.replaceAll("|", "\\|")} |`,
    )
    .join("\n") +
  "\n";
for (const [path, text] of Object.entries({
  "contracts/openapi.json": JSON.stringify(spec, null, 2) + "\n",
  "lib/client/schema.d.ts":
    "// Generated by npm run api:generate. Do not edit by hand.\n" + types,
  "docs/API_ENDPOINTS.md": index,
})) {
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== text)
      throw new Error(path + " is stale; run npm run api:generate");
  } else writeFileSync(path, text);
}
